### ISSUE TITLE
Compatability

### ISSUE THREAD

**Issue by jng2398** [Francesco149/wxPloiter#3]
Anyway to recompile this and downgrade to an older version of kMS? Mainly v65 hue

**Comment by jng2398** [comment]
Currently its the IAT pointer for recv that cannot be found.

**Comment by Francesco149** [comment]
yes, remove the bypassless hooks and just hook send/recv normally.

**Comment by jng2398** [comment]
After recompiling without bypassless hooks, I'm still receiving this.

11:47:54: Could not find the IAT pointer for recv. Recv log will not work.
11:47:54: Could not find the virtualized send function. Falling back to decrypting raw winsock packets (not very reliable but better than nothing).
11:47:54: Falling back to decrypting winsock packets.

**Comment by Francesco149** [comment]
recv hook is also a bypassless hook
you have to rewrite that to hook recv directly. or pointer scan for something that points to the recv function and update it.

**Comment by jng2398** [comment]
Having issues, I have no idea what I'm doing o 3 o

Could I just issue some commission for your work :(

**Comment by Francesco149** [comment]
nah, I don't feel like working on this codebase anymore
